# Generated by Django 3.1.1 on 2020-09-04 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turfapi', '0004_turf_turf_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
