# Generated by Django 3.1.1 on 2020-09-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapi', '0005_organization_org_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_type',
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
