# Generated by Django 3.1.1 on 2020-09-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfapi', '0006_auto_20200904_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_user',
        ),
    ]
