# Generated by Django 3.1.1 on 2020-09-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapi', '0008_auto_20200910_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
