# Generated by Django 3.1.1 on 2020-09-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapi', '0010_auto_20200910_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('MOBILE MONEY', 'Mobile Money'), ('CASH', 'Cash')], default='CASH', max_length=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_paid', 'Not Paid'), ('complete', 'Complete')], default='pending', max_length=8),
        ),
    ]
