# Generated by Django 3.1.1 on 2020-09-11 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapi', '0011_auto_20200911_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_booked',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
