# Generated by Django 3.1.1 on 2020-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapi', '0014_auto_20200912_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='turf_image',
        ),
        migrations.AddField(
            model_name='turf',
            name='image_url',
            field=models.URLField(default='http://defaulturl.com', max_length=255),
            preserve_default=False,
        ),
    ]
