version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true

      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache: 
          key: deps9-{{.Branch}}-{{checksum  "Pipfile.lock"}}
      - run:
          name: Install dependencies
          command:  |
            pip install pipenv
            pipenv install
            pipenv install -d
            
      - save-cache:
          key: deps9-{{ .Branch}}-{{checksum "Pipfile.lock"}}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          name: Run tests and generate report 
          command: |
            pipenv run coverage run --source . --omit=*/venv/*,*/migrations/* manage.py test
            pipenv run coverage html
      - store_artifacts:
          path: ".coverage.html_report"
      
      




    