version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/circle_test
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache: 
          key: deps9-{{.Branch}}-{{checksum  "Pipfile.lock"}}
      - run:
          command:  |
            pip install pipenv
            pipenv install
      - save-cache:
          key: deps9-{{ .Branch}}-{{checksum "Pipfile.lock"}}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          command: |
            pipenv run python manage.py test
      - store_test_results:
          path: test-results
      




    